-- Supabase Schema for Digital Heroes Platform

-- 1. Profiles Table (extends Supabase auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text default 'subscriber' check (role in ('subscriber', 'admin')),
  subscription_status text default 'inactive' check (subscription_status in ('active', 'inactive', 'canceled')),
  subscription_plan text check (subscription_plan in ('monthly', 'yearly')),
  charity_id bigint, -- references charities(id)
  charity_percentage integer default 10 check (charity_percentage >= 10 and charity_percentage <= 100),
  total_won numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security
alter table public.profiles enable row level security;

-- Create policies for profiles
create policy "Users can view their own profile." on public.profiles for select using (auth.uid() = id);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);
create policy "Admins can view all profiles." on public.profiles for select using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 2. Charities Table
create table public.charities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  logo_url text,
  featured boolean default false,
  total_raised numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.charities enable row level security;
create policy "Charities are viewable by everyone." on public.charities for select using (true);
create policy "Admins can manage charities." on public.charities for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 3. Golf Scores Table
-- Enforcing the logic: duplicate scores for the same date are not allowed.
create table public.golf_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  score integer not null check (score >= 1 and score <= 45),
  played_at date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, played_at) -- constraint: Only one score entry is permitted per date
);

alter table public.golf_scores enable row level security;
create policy "Users can manage their own scores." on public.golf_scores for all using (auth.uid() = user_id);
create policy "Admins can view all scores." on public.golf_scores for select using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 4. Draws Table
create table public.draws (
  id bigint generated by default as identity primary key,
  draw_date date not null,
  status text default 'pending' check (status in ('pending', 'simulated', 'published')),
  winning_numbers integer[] not null,
  total_prize_pool numeric default 0,
  jackpot_amount numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.draws enable row level security;
create policy "Published draws are viewable by everyone." on public.draws for select using (status = 'published');
create policy "Admins can manage draws." on public.draws for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 5. Winners Table
create table public.winners (
  id bigint generated by default as identity primary key,
  draw_id bigint references public.draws(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  match_type text check (match_type in ('3-match', '4-match', '5-match')),
  prize_amount numeric not null,
  proof_url text, -- For uploading the screenshot
  status text default 'pending' check (status in ('pending', 'verified', 'paid', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.winners enable row level security;
create policy "Users can view their own winning records." on public.winners for select using (auth.uid() = user_id);
create policy "Users can update their proof of winning." on public.winners for update using (auth.uid() = user_id);
create policy "Admins can manage winners." on public.winners for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);
